#!/usr/bin/env python3
"""Mapa repozytorium Danaco Console.

Buduje zwięzły, deterministyczny obraz dużego repozytorium (Go + TypeScript + Rust),
żeby orientacja kosztowała jedno czytanie zamiast dziesiątek wyszukiwań.

Użycie:
    python3 repo_map.py --root . --out REPOMAP.md
    python3 repo_map.py --root . --top 30

Zależności: wyłącznie biblioteka standardowa Pythona 3.9+.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

# Katalogi pomijane w obu narzędziach tej umiejętności. `gen` to katalog schematów
# generowanych przez Tauri, nie kod pisany ręcznie. Listę nadpiszesz przez --skip.
SKIP_DIRS = {
    ".git", "node_modules", "target", "dist", "build", "vendor", ".venv", "venv",
    "__pycache__", ".next", ".turbo", "coverage", ".idea", ".vscode", "gen",
}

LANG_BY_EXT = {
    ".go": "Go", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript",
    ".mjs": "JavaScript", ".rs": "Rust", ".css": "CSS", ".html": "HTML",
    ".json": "JSON", ".md": "Markdown", ".sql": "SQL", ".py": "Python",
}

GO_PACKAGE = re.compile(r"^package\s+(\w+)", re.M)
GO_IMPORT_BLOCK = re.compile(r"^import\s*\(([^)]*)\)", re.M | re.S)
GO_IMPORT_ONE = re.compile(r'^import\s+(?:\w+\s+)?"([^"]+)"', re.M)
GO_IMPORT_LINE = re.compile(r'^\s*(?:[\w.]+\s+)?"([^"]+)"', re.M)
TS_IMPORT = re.compile(r'(?:^|\n)\s*(?:import|export)[^;\n]*?from\s+["\']([^"\']+)["\']')
TS_DYNAMIC = re.compile(r'import\(\s*["\']([^"\']+)["\']\s*\)')
# Nagłówek plików generowanych. Nasze generatory piszą "NIE EDYTOWAĆ RĘCZNIE" z polskimi
# znakami, więc wzorzec musi je obejmować - inaczej sekcja plików generowanych jest pusta.
GENERATED = re.compile(r"NIE EDYTOWA[ĆC]|Code generated by|@generated|autogenerated|"
                       r"Kod generowany automatycznie", re.I)


def iter_files(root: Path, skip=SKIP_DIRS):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in skip and not d.startswith("."))
        for name in sorted(filenames):
            path = Path(dirpath) / name
            if path.suffix in LANG_BY_EXT:
                yield path


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def go_module_path(root: Path) -> str:
    gomod = root / "go.mod"
    if gomod.exists():
        m = re.search(r"^module\s+(\S+)", read(gomod), re.M)
        if m:
            return m.group(1)
    return ""


def go_imports(src: str):
    out = []
    for block in GO_IMPORT_BLOCK.findall(src):
        out.extend(GO_IMPORT_LINE.findall(block))
    out.extend(GO_IMPORT_ONE.findall(src))
    return out


def ts_resolve(importer: Path, spec: str, root: Path):
    """Zamienia specyfikator względny na ścieżkę pliku; zwraca None dla pakietów zewnętrznych."""
    if not spec.startswith("."):
        return None
    base = (importer.parent / spec).resolve()
    for cand in (base, base.with_suffix(".ts"), base.with_suffix(".tsx"),
                 Path(str(base) + ".ts"), Path(str(base) + ".tsx"),
                 base / "index.ts", base / "index.tsx"):
        if cand.is_file():
            try:
                return cand.relative_to(root)
            except ValueError:
                return None
    return None


def odmiana(n: int, jeden: str, kilka: str, wiele: str) -> str:
    """Polska odmiana liczebnika: 1 pakiet, 2-4 pakiety, 5+ pakietów."""
    if n == 1:
        return jeden
    reszta10, reszta100 = n % 10, n % 100
    if 2 <= reszta10 <= 4 and not 12 <= reszta100 <= 14:
        return kilka
    return wiele


def human(n: int) -> str:
    return "{:,}".format(n).replace(",", " ")


def build(root: Path, skip=SKIP_DIRS):
    stats = defaultdict(lambda: {"files": 0, "lines": 0})
    files = []
    go_pkgs = defaultdict(lambda: {"files": 0, "lines": 0, "name": "", "imports": set()})
    ts_edges = defaultdict(set)
    generated = []
    top_dirs = defaultdict(lambda: {"files": 0, "lines": 0})

    modpath = go_module_path(root)

    for path in iter_files(root, skip):
        rel = path.relative_to(root)
        src = read(path)
        lines = src.count("\n") + (0 if src.endswith("\n") or not src else 1)
        lang = LANG_BY_EXT[path.suffix]
        stats[lang]["files"] += 1
        stats[lang]["lines"] += lines
        files.append((rel, lines, lang))
        top = rel.parts[0] if len(rel.parts) > 1 else "(korzeń)"
        top_dirs[top]["files"] += 1
        top_dirs[top]["lines"] += lines
        if GENERATED.search(src[:2000]):
            generated.append(rel)

        if path.suffix == ".go" and not path.name.endswith("_test.go"):
            pkgdir = rel.parent.as_posix()
            info = go_pkgs[pkgdir]
            info["files"] += 1
            info["lines"] += lines
            m = GO_PACKAGE.search(src)
            if m:
                info["name"] = m.group(1)
            for imp in go_imports(src):
                if modpath and imp.startswith(modpath):
                    inner = imp[len(modpath):].lstrip("/")
                    info["imports"].add(inner or ".")
        elif path.suffix in (".ts", ".tsx"):
            for spec in list(TS_IMPORT.findall(src)) + list(TS_DYNAMIC.findall(src)):
                target = ts_resolve(path, spec, root)
                if target:
                    ts_edges[rel.as_posix()].add(target.as_posix())

    return {
        "stats": stats, "files": files, "go_pkgs": go_pkgs, "ts_edges": ts_edges,
        "generated": generated, "top_dirs": top_dirs, "modpath": modpath,
    }


def w_korzeniu(root: Path, wzgledna: str, opis: str) -> Path:
    """Ścieżka wyjściowa ograniczona do korzenia repozytorium."""
    if Path(wzgledna).is_absolute():
        print("BŁĄD: {} ({}) jest ścieżką absolutną - podawaj ścieżkę względną wobec "
              "--root".format(opis, wzgledna), file=sys.stderr)
        sys.exit(4)
    cel = (root / wzgledna).resolve()
    if cel != root and root not in cel.parents:
        print("BŁĄD: {} ({}) wskazuje poza {}".format(opis, wzgledna, root), file=sys.stderr)
        sys.exit(4)
    return cel


def zapisz_atomowo(cel: Path, tresc: str) -> None:
    """Zapis przez plik tymczasowy i podmianę: przerwany zapis nie zostawia
    obciętej mapy repozytorium na miejscu poprzedniej."""
    cel.parent.mkdir(parents=True, exist_ok=True)
    tymczasowy = cel.with_name(cel.name + ".tmp-repo-map")
    tymczasowy.write_text(tresc, encoding="utf-8")
    os.replace(tymczasowy, cel)


def render(data, top: int) -> str:
    out = []
    w = out.append
    stats = data["stats"]
    total_files = sum(s["files"] for s in stats.values())
    total_lines = sum(s["lines"] for s in stats.values())

    w("# Mapa repozytorium")
    w("")
    w("Plik generowany przez `repo_map.py`. Nie edytuj ręcznie — uruchom narzędzie ponownie.")
    w("")
    w("Razem: **{} plików**, **{} linii**.".format(human(total_files), human(total_lines)))
    w("")
    w("## Języki")
    w("")
    w("| Język | Plików | Linii |")
    w("|---|---:|---:|")
    for lang, s in sorted(stats.items(), key=lambda kv: -kv[1]["lines"]):
        w("| {} | {} | {} |".format(lang, human(s["files"]), human(s["lines"])))
    w("")

    w("## Obszary najwyższego poziomu")
    w("")
    w("| Katalog | Plików | Linii |")
    w("|---|---:|---:|")
    for name, s in sorted(data["top_dirs"].items(), key=lambda kv: -kv[1]["lines"]):
        w("| `{}` | {} | {} |".format(name, human(s["files"]), human(s["lines"])))
    w("")

    go_pkgs = data["go_pkgs"]
    if go_pkgs:
        importers = defaultdict(set)
        for pkg, info in go_pkgs.items():
            for dep in info["imports"]:
                importers[dep].add(pkg)
        w("## Pakiety Go")
        w("")
        w("Moduł: `{}`. Kolumna *zależy od* oznacza zależności wewnętrzne, *używany przez* — "
          "ile pakietów w repozytorium go importuje.".format(data["modpath"] or "(brak go.mod)"))
        w("")
        w("| Pakiet | Nazwa | Plików | Linii | Zależy od | Używany przez |")
        w("|---|---|---:|---:|---:|---:|")
        for pkg, info in sorted(go_pkgs.items(), key=lambda kv: -kv[1]["lines"])[:top]:
            w("| `{}` | {} | {} | {} | {} | {} |".format(
                pkg, info["name"] or "?", info["files"], human(info["lines"]),
                len(info["imports"]), len(importers.get(pkg, ()))))
        if len(go_pkgs) > top:
            w("")
            w("_(pokazano {} z {} pakietów; użyj `--top`, aby zobaczyć więcej)_".format(top, len(go_pkgs)))
        w("")
        wezly = sorted(importers.items(), key=lambda kv: -len(kv[1]))[:10]
        if wezly:
            w("### Węzły — pakiety, których zmiana dotyka najwięcej innych")
            w("")
            for pkg, users in wezly:
                w("- `{}` — importowany przez {} {}".format(
                    pkg, len(users), odmiana(len(users), "pakiet", "pakiety", "pakietów")))
            w("")
            w("Zmiana w węźle wymaga szerszej weryfikacji niż zmiana w liściu. Sprawdź zasięg"
              " narzędziem `impact.py` przed edycją.")
            w("")

        # Diagram zależności - czytelny tylko przy rozsądnej liczbie pakietów.
        # Powyżej ~40 węzłów mermaid produkuje plątaninę, w której nic nie widać,
        # więc wtedy uczciwiej pokazać samą tabelę.
        if len(go_pkgs) <= 40:
            w("### Diagram zależności pakietów Go")
            w("")
            w("```mermaid")
            w("graph LR")
            skroty = {}
            for i, pkg in enumerate(sorted(go_pkgs)):
                skroty[pkg] = "p{}".format(i)
                etykieta = pkg.split("/")[-1] if "/" in pkg else pkg
                w('  {}["{}"]'.format(skroty[pkg], etykieta))
            for pkg, info in sorted(go_pkgs.items()):
                for dep in sorted(info["imports"]):
                    if dep in skroty:
                        w("  {} --> {}".format(skroty[pkg], skroty[dep]))
            w("```")
            w("")
            w("Strzałka prowadzi od pakietu importującego do importowanego. Cykl na tym"
              " diagramie oznacza kod, którego Go nie skompiluje.")
            w("")

    ts_edges = data["ts_edges"]
    if ts_edges:
        fan_in = defaultdict(int)
        for src, targets in ts_edges.items():
            for t in targets:
                fan_in[t] += 1
        w("## TypeScript — moduły o największym zasięgu")
        w("")
        w("| Moduł | Importowany przez |")
        w("|---|---:|")
        for mod, count in sorted(fan_in.items(), key=lambda kv: -kv[1])[:min(top, 15)]:
            w("| `{}` | {} |".format(mod, count))
        w("")

    big = sorted(data["files"], key=lambda f: -f[1])[:min(top, 20)]
    if big:
        w("## Największe pliki")
        w("")
        w("| Plik | Linii | Język |")
        w("|---|---:|---|")
        for rel, lines, lang in big:
            w("| `{}` | {} | {} |".format(rel.as_posix(), human(lines), lang))
        w("")
        w("Plik powyżej ~800 linii zwykle łączy kilka odpowiedzialności. Przy pracy w takim pliku"
          " czytaj wycinkiem (`sed -n`), nie całością — inaczej zajmie połowę dostępnego kontekstu.")
        w("")

    if data["generated"]:
        w("## Pliki generowane — nie edytuj ręcznie")
        w("")
        for rel in data["generated"][:min(top, 25)]:
            w("- `{}`".format(rel.as_posix()))
        w("")
        w("Zmiany w tych plikach znikają przy najbliższej regeneracji. Edytuj źródło, z którego"
          " powstają.")
        w("")

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generuje mapę repozytorium w Markdownie")
    ap.add_argument("--root", default=".", help="korzeń repozytorium")
    ap.add_argument("--top", type=int, default=25, help="ile pozycji w tabelach")
    ap.add_argument("--out", help="plik wyjściowy, względem --root (domyślnie standardowe wyjście)")
    ap.add_argument("--skip", action="append", default=[],
                    help="dodatkowy katalog do pominięcia (można podać wiele razy)")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print("BŁĄD: {} nie jest katalogiem".format(root), file=sys.stderr)
        return 4
    if args.top < 1:
        print("BŁĄD: --top musi być dodatnie", file=sys.stderr)
        return 4

    data = build(root, SKIP_DIRS | set(args.skip))
    md = render(data, args.top)
    if args.out:
        cel = w_korzeniu(root, args.out, "--out")
        try:
            zapisz_atomowo(cel, md)
        except OSError as blad:
            print("BŁĄD: nie udało się zapisać {}: {}".format(cel, blad), file=sys.stderr)
            return 4
        print("zapisano {}".format(cel), file=sys.stderr)
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
